// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUhYJ5EJdUT_3d4jZKcPi-uzZGtD_LhRE',
    appId: '1:623324366198:web:ad21fbf6e1a7b98758e657',
    messagingSenderId: '623324366198',
    projectId: 'budgeit-fc659',
    authDomain: 'budgeit-fc659.firebaseapp.com',
    storageBucket: 'budgeit-fc659.appspot.com',
    measurementId: 'G-MEM8P5JJT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDii1f2Hupv9St2BXVBZGHCbXDHnWPRsOs',
    appId: '1:623324366198:android:cd7c05c07099c24758e657',
    messagingSenderId: '623324366198',
    projectId: 'budgeit-fc659',
    storageBucket: 'budgeit-fc659.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Kj4v8J_5Ad8vOfTNnwYFHSFVTvDFYqU',
    appId: '1:623324366198:ios:ae5ff45c0ba1f3ad58e657',
    messagingSenderId: '623324366198',
    projectId: 'budgeit-fc659',
    storageBucket: 'budgeit-fc659.appspot.com',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Kj4v8J_5Ad8vOfTNnwYFHSFVTvDFYqU',
    appId: '1:623324366198:ios:ae5ff45c0ba1f3ad58e657',
    messagingSenderId: '623324366198',
    projectId: 'budgeit-fc659',
    storageBucket: 'budgeit-fc659.appspot.com',
    iosBundleId: 'com.example.moneyTracker',
  );
}
